[versions]
android-gradle-plugin = "8.3.2"
kotlin = "1.7.10"
compileSdk = "34"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.2.1" }
junit = { module = "junit:junit", version = "4.13.2" }
robolectric = { module = "org.robolectric:robolectric", version = "4.14.1" }
mockk = { module = "io.mockk:mockk", version = "1.13.3" }
truth = { module = "com.google.truth:truth", version = "1.4.4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.32.0" }
